### ISSUE TITLE
Frame Strata Disregards SavedVariables Setting

### ISSUE THREAD

**Issue by Cilraaz** [SimCMinMax/AethysRotation#63]
I'm using Aethys over top of a set of WeakAuras.  On default settings, the icon is under the set of WAs.  If I go into settings and move the Aethys icon to "HIGH" strata, then reload, it remains below the set of WAs.  I have confirmed that the SavedVariables then shows AethysRotationDB.GUISettings.General.MainFrameStrata is set to "HIGH".  If I then edit Interface\Addons\AethysRotation\Settings.lua and set the default settings to use a MainFrameStrata of "HIGH", the Aeythis icon is layered properly and shows on top of the WAs.

**Comment by Kutikuti** [comment]
Fixed with https://github.com/SimCMinMax/AethysRotation/commit/53f577c5169dac22b9ad38fe66e1d0ce05bc4cf9

@Aethys256 the framestrata settings were not loaded with the first SetFrameStrata (https://github.com/SimCMinMax/AethysRotation/blob/53f577c5169dac22b9ad38fe66e1d0ce05bc4cf9/AethysRotation/Main.lua#L31)

So I added a second one later, once the settings are loaded. Dunno if I had to remove the first one.
