### ISSUE TITLE
Warlock green fire icon bug

### ISSUE THREAD

**Issue by Yaiklai** [SimCMinMax/AethysRotation#66]
If i got the green fire activated as destro warlock, the "Auto/Green" Spell Icons setting doesn't actually work for me. The first spell i cast (Immolate) will be green, but then it starts switching to orange spells.

**Comment by Kutikuti** [comment]
Found the issue. It will be fixed in the next update.
Thanks for the report.



If you want to manually fix the issue before the update, change those lines : 
https://github.com/SimCMinMax/AethysRotation/blob/master/AethysRotation_Warlock/Destruction.lua#L176
if Settings.Commons.SpellType=="Auto" then --auto
TO : if Settings.Destruction.SpellType=="Auto" then --auto

and https://github.com/SimCMinMax/AethysRotation/blob/master/AethysRotation_Warlock/Destruction.lua#L181
elseif Settings.Commons.SpellType=="Green" then --green
TO : elseif Settings.Destruction.SpellType=="Green" then --green
